#!/usr/bin/env python3
"""Generate Elm character predicates and lowercase mappings.

Elm 0.19.1 was built with GHC 8.4.3 (tables from WCsubst.c). Elm 0.19.2 and
0.19.3 were built with GHC 9.8.4 and 9.10.3, whose base library derives the
same predicates from the Unicode 15.1.0 general categories.

Requires Python and a C compiler only when regenerating, never at build/runtime.
The pinned upstream source is verified before compiling the generator.
"""
import argparse
import hashlib
from pathlib import Path
import subprocess
import tempfile
import urllib.request

URL = 'https://raw.githubusercontent.com/ghc/ghc/ghc-8.4.3-release/libraries/base/cbits/WCsubst.c'
SHA256 = '4f5893748fe80246058f21a6bb8da62bff06857ad9c8e32c278f2b6d142c2068'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source', type=Path, help='Local copy of the pinned WCsubst.c (SHA-256 still verified)')
parser.add_argument('--unicode-data', type=Path, help='Local copy of the pinned UnicodeData.txt (SHA-256 still verified)')
args = parser.parse_args()
source = args.source.read_bytes() if args.source else urllib.request.urlopen(URL, timeout=30).read()
assert hashlib.sha256(source).hexdigest() == SHA256
with tempfile.TemporaryDirectory(prefix='elm-unicode-') as directory:
    root = Path(directory)
    # HsInt has pointer width; no Haskell runtime is needed for these pure tables.
    code = source.decode().replace('#include "WCsubst.h"', '#include <stdlib.h>\n#include <stdint.h>\n#include <stdio.h>\ntypedef intptr_t HsInt;')
    code += '\nint main(int argc, char** argv) { if (argc > 1) { for (int c=0; c<0x110000; c++) if (u_towlower(c) != c) printf("%X %X\\n", c, (unsigned int)u_towlower(c)); return 0; } for (int c=0; c<0x110000; c++) putchar((!!u_iswlower(c)) | ((!!u_iswupper(c))<<1) | ((!!u_iswalpha(c))<<2) | ((!!u_iswalnum(c))<<3) | ((!!u_iswspace(c))<<4)); return 0; }\n'
    (root/'table.c').write_text(code)
    subprocess.run(['cc','-O2',str(root/'table.c'),'-o',str(root/'table')],check=True)
    flags = subprocess.check_output([str(root/'table')])
    lowercase = [tuple(int(x,16) for x in line.split()) for line in subprocess.check_output([str(root/'table'), 'lower']).decode().splitlines()]
    assert all(0 <= a <= 0x10ffff and 0 <= b <= 0x10ffff and not 0xd800 <= b <= 0xdfff for a,b in lowercase)
assert len(flags) == 0x110000
ranges = []
start = 0
for end in range(1, len(flags)+1):
    if end == len(flags) or flags[end] != flags[start]:
        if flags[start]:
            ranges.append((start,end-1,flags[start]))
        start = end
out = '''//! Generated by scripts/generate_unicode.py; do not hand-edit.
//! GHC 8.4.3 character categories used by the official Elm 0.19.1 binary.
//! Derived from WCsubst.c (GHC base); see LICENSE-GHC for attribution/license.
// Source SHA-256: ''' + SHA256 + '''

fn flags(c: char) -> u8 {
    let ranges = if crate::edition::unicode_15_1() { crate::unicode_15_1::RANGES } else { RANGES };
    let c = c as u32;
    let i = ranges.partition_point(|&(start, _, _)| start <= c);
    if i == 0 { return 0; }
    let (_, end, flags) = ranges[i - 1];
    if c <= end { flags } else { 0 }
}
pub fn is_lower(c: char) -> bool { if c.is_ascii() { c.is_ascii_lowercase() } else { flags(c) & 1 != 0 } }
pub fn is_upper(c: char) -> bool { if c.is_ascii() { c.is_ascii_uppercase() } else { flags(c) & 2 != 0 } }
pub fn is_alpha(c: char) -> bool { if c.is_ascii() { c.is_ascii_alphabetic() } else { flags(c) & 4 != 0 } }
pub fn is_alphanumeric(c: char) -> bool { if c.is_ascii() { c.is_ascii_alphanumeric() } else { flags(c) & 8 != 0 } }
pub fn is_space(c: char) -> bool { matches!(c, '\\t'..='\\r' | ' ') || flags(c) & 16 != 0 }
/// GHC's one-character lowercase mapping, independent of Rust's Unicode version.
pub fn to_lower(c: char) -> char {
    if c.is_ascii() { return c.to_ascii_lowercase(); }
    let lowercase = if crate::edition::unicode_15_1() { crate::unicode_15_1::LOWERCASE } else { LOWERCASE };
    match lowercase.binary_search_by_key(&(c as u32), |&(source, _)| source) {
        Ok(index) => char::from_u32(lowercase[index].1).expect("generated Unicode scalar"),
        Err(_) => c,
    }
}
const RANGES: &[(u32, u32, u8)] = &[
'''
out += ''.join(f'    (0x{a:X}, 0x{b:X}, {f}),\n' for a,b,f in ranges) + '];\n'
out += 'const LOWERCASE: &[(u32, u32)] = &[\n' + ''.join(f'    (0x{a:X}, 0x{b:X}),\n' for a,b in lowercase) + '];\n'
path = Path(__file__).resolve().parents[1]/'src/unicode.rs'
path.write_text(out)
subprocess.run(['rustfmt','--edition','2024',str(path)],check=True)
print(f'{len(ranges)} category ranges and {len(lowercase)} lowercase mappings written to {path}')

# Unicode 15.1.0, as bundled with the GHC releases that built Elm 0.19.2 and 0.19.3.
# GHC.Unicode defines the predicates on general categories:
#   isLower = Ll, isUpper = Lu | Lt, isAlpha = L*, isAlphaNum = L* | N*, isSpace = Zs.
UCD_URL = 'https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt'
UCD_SHA256 = '2fc713e6a31a87c4850a37fe2caffa4218180fadb5de86b43a143ddb4581fb86'
data = args.unicode_data.read_bytes() if args.unicode_data else urllib.request.urlopen(UCD_URL, timeout=30).read()
assert hashlib.sha256(data).hexdigest() == UCD_SHA256
LETTERS = {'Lu', 'Ll', 'Lt', 'Lm', 'Lo'}
def category_flags(category):
    value = 0
    if category == 'Ll': value |= 1
    if category in ('Lu', 'Lt'): value |= 2
    if category in LETTERS: value |= 4
    if category in LETTERS or category in ('Nd', 'Nl', 'No'): value |= 8
    if category == 'Zs': value |= 16
    return value
modern = bytearray(0x110000)
lowercase = []
first = None
for line in data.decode().splitlines():
    fields = line.split(';')
    code = int(fields[0], 16)
    if fields[1].endswith(', First>'):
        first = code
        continue
    start = first if fields[1].endswith(', Last>') else code
    first = None
    for point in range(start, code + 1):
        modern[point] = category_flags(fields[2])
    if fields[13]:
        lowercase.append((code, int(fields[13], 16)))
ranges = []
start = 0
for end in range(1, len(modern)+1):
    if end == len(modern) or modern[end] != modern[start]:
        if modern[start]:
            ranges.append((start,end-1,modern[start]))
        start = end
out = '''//! Generated by scripts/generate_unicode.py; do not hand-edit.
//! Unicode 15.1.0 character categories, as used by the GHC releases that
//! built the official Elm 0.19.2 and 0.19.3 binaries. See LICENSE-GHC.
// Source SHA-256: ''' + UCD_SHA256 + '''

pub(crate) const RANGES: &[(u32, u32, u8)] = &[
'''
out += ''.join(f'    (0x{a:X}, 0x{b:X}, {f}),\n' for a,b,f in ranges) + '];\n'
out += 'pub(crate) const LOWERCASE: &[(u32, u32)] = &[\n' + ''.join(f'    (0x{a:X}, 0x{b:X}),\n' for a,b in sorted(lowercase)) + '];\n'
path = Path(__file__).resolve().parents[1]/'src/unicode_15_1.rs'
path.write_text(out)
subprocess.run(['rustfmt','--edition','2024',str(path)],check=True)
print(f'{len(ranges)} category ranges and {len(lowercase)} lowercase mappings written to {path}')
