#!/usr/bin/env python3
"""Generate Elm 0.19.1 character predicates and lowercase mappings from GHC 8.4.3.

Requires Python and a C compiler only when regenerating, never at build/runtime.
The pinned upstream source is verified before compiling the generator.
"""
import argparse
import hashlib
from pathlib import Path
import subprocess
import tempfile
import urllib.request

URL = 'https://raw.githubusercontent.com/ghc/ghc/ghc-8.4.3-release/libraries/base/cbits/WCsubst.c'
SHA256 = '4f5893748fe80246058f21a6bb8da62bff06857ad9c8e32c278f2b6d142c2068'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source', type=Path, help='Local copy of the pinned WCsubst.c (SHA-256 still verified)')
args = parser.parse_args()
source = args.source.read_bytes() if args.source else urllib.request.urlopen(URL, timeout=30).read()
assert hashlib.sha256(source).hexdigest() == SHA256
with tempfile.TemporaryDirectory(prefix='elm-unicode-') as directory:
    root = Path(directory)
    # HsInt has pointer width; no Haskell runtime is needed for these pure tables.
    code = source.decode().replace('#include "WCsubst.h"', '#include <stdlib.h>\n#include <stdint.h>\n#include <stdio.h>\ntypedef intptr_t HsInt;')
    code += '\nint main(int argc, char** argv) { if (argc > 1) { for (int c=0; c<0x110000; c++) if (u_towlower(c) != c) printf("%X %X\\n", c, (unsigned int)u_towlower(c)); return 0; } for (int c=0; c<0x110000; c++) putchar((!!u_iswlower(c)) | ((!!u_iswupper(c))<<1) | ((!!u_iswalpha(c))<<2) | ((!!u_iswalnum(c))<<3) | ((!!u_iswspace(c))<<4)); return 0; }\n'
    (root/'table.c').write_text(code)
    subprocess.run(['cc','-O2',str(root/'table.c'),'-o',str(root/'table')],check=True)
    flags = subprocess.check_output([str(root/'table')])
    lowercase = [tuple(int(x,16) for x in line.split()) for line in subprocess.check_output([str(root/'table'), 'lower']).decode().splitlines()]
    assert all(0 <= a <= 0x10ffff and 0 <= b <= 0x10ffff and not 0xd800 <= b <= 0xdfff for a,b in lowercase)
assert len(flags) == 0x110000
ranges = []
start = 0
for end in range(1, len(flags)+1):
    if end == len(flags) or flags[end] != flags[start]:
        if flags[start]:
            ranges.append((start,end-1,flags[start]))
        start = end
out = '''//! Generated by scripts/generate_unicode.py; do not hand-edit.
//! GHC 8.4.3 character categories used by the official Elm 0.19.1 binary.
//! Derived from WCsubst.c (GHC base); see LICENSE-GHC for attribution/license.
// Source SHA-256: ''' + SHA256 + '''

fn flags(c: char) -> u8 {
    let c = c as u32;
    let i = RANGES.partition_point(|&(start, _, _)| start <= c);
    if i == 0 { return 0; }
    let (_, end, flags) = RANGES[i - 1];
    if c <= end { flags } else { 0 }
}
pub fn is_lower(c: char) -> bool { if c.is_ascii() { c.is_ascii_lowercase() } else { flags(c) & 1 != 0 } }
pub fn is_upper(c: char) -> bool { if c.is_ascii() { c.is_ascii_uppercase() } else { flags(c) & 2 != 0 } }
pub fn is_alpha(c: char) -> bool { if c.is_ascii() { c.is_ascii_alphabetic() } else { flags(c) & 4 != 0 } }
pub fn is_alphanumeric(c: char) -> bool { if c.is_ascii() { c.is_ascii_alphanumeric() } else { flags(c) & 8 != 0 } }
pub fn is_space(c: char) -> bool { matches!(c, '\\t'..='\\r' | ' ') || flags(c) & 16 != 0 }
/// GHC's one-character lowercase mapping, independent of Rust's Unicode version.
pub fn to_lower(c: char) -> char {
    if c.is_ascii() { return c.to_ascii_lowercase(); }
    match LOWERCASE.binary_search_by_key(&(c as u32), |&(source, _)| source) {
        Ok(index) => char::from_u32(LOWERCASE[index].1).expect("generated Unicode scalar"),
        Err(_) => c,
    }
}
const RANGES: &[(u32, u32, u8)] = &[
'''
out += ''.join(f'    (0x{a:X}, 0x{b:X}, {f}),\n' for a,b,f in ranges) + '];\n'
out += 'const LOWERCASE: &[(u32, u32)] = &[\n' + ''.join(f'    (0x{a:X}, 0x{b:X}),\n' for a,b in lowercase) + '];\n'
path = Path(__file__).resolve().parents[1]/'src/unicode.rs'
path.write_text(out)
subprocess.run(['rustfmt','--edition','2024',str(path)],check=True)
print(f'{len(ranges)} category ranges and {len(lowercase)} lowercase mappings written to {path}')
